// <auto-generated />
namespace AutoMarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _35 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_35));
        
        string IMigrationMetadata.Id
        {
            get { return "202407190021248_3.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
