spring:
  jpa:
    show-sql: true

logging:
  level:
    com.automarket: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%-5level){highlight} %clr([%X{requestId}]){cyan} %clr(%logger{36}){magenta} - %msg%n"
